version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
s3_bucket = "tpm-learning-sam-cli-bucket"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
